2020-11-18 10:29:14,800 INFO    MainThread:5137 [internal.py:wandb_internal():63] W&B internal server running at pid: 5137
2020-11-18 10:29:14,802 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: check_version
2020-11-18 10:29:14,802 INFO    WriterThread:5137 [datastore.py:open_for_write():76] open: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/run-x7es5chb.wandb
2020-11-18 10:29:14,802 DEBUG   SenderThread:5137 [sender.py:send():90] send: header
2020-11-18 10:29:14,802 DEBUG   SenderThread:5137 [sender.py:send():90] send: request
2020-11-18 10:29:14,803 DEBUG   SenderThread:5137 [sender.py:send_request():99] send_request: check_version
2020-11-18 10:29:14,804 DEBUG   Thread-4  :5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): pypi.org:443
2020-11-18 10:29:14,865 DEBUG   Thread-4  :5137 [connectionpool.py:_make_request():452] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 51661
2020-11-18 10:29:14,902 DEBUG   SenderThread:5137 [sender.py:send():90] send: run
2020-11-18 10:29:14,930 DEBUG   SenderThread:5137 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-18 10:29:14,964 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:29:15,363 DEBUG   SenderThread:5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:29:15,380 INFO    SenderThread:5137 [dir_watcher.py:__init__():164] watching files in: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files
2020-11-18 10:29:15,380 INFO    SenderThread:5137 [sender.py:_start_run_threads():487] run started: x7es5chb with start time 1605675554
2020-11-18 10:29:15,381 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: run_start
2020-11-18 10:29:15,383 DEBUG   SenderThread:5137 [sender.py:send():90] send: summary
2020-11-18 10:29:15,385 INFO    SenderThread:5137 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2020-11-18 10:29:15,395 DEBUG   HandlerThread:5137 [cmd.py:execute():718] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration, universal_newlines=False, shell=None, istream=<valid stream>)
2020-11-18 10:29:15,410 DEBUG   HandlerThread:5137 [cmd.py:execute():718] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration, universal_newlines=False, shell=None, istream=None)
2020-11-18 10:29:15,567 DEBUG   SenderThread:5137 [sender.py:send():90] send: files
2020-11-18 10:29:15,567 INFO    SenderThread:5137 [sender.py:_save_file():568] saving file wandb-metadata.json with policy now
2020-11-18 10:29:15,571 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: status
2020-11-18 10:29:15,572 DEBUG   Thread-11 :5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:29:15,572 DEBUG   SenderThread:5137 [sender.py:send():90] send: request
2020-11-18 10:29:15,572 DEBUG   SenderThread:5137 [sender.py:send_request():99] send_request: status
2020-11-18 10:29:15,574 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:29:15,923 DEBUG   SenderThread:5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:29:15,944 DEBUG   Thread-11 :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:29:15,949 DEBUG   Thread-11 :5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-18 10:29:16,381 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_created():212] file/dir created: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/output.log
2020-11-18 10:29:16,381 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_created():212] file/dir created: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/wandb-summary.json
2020-11-18 10:29:16,381 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_created():212] file/dir created: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/wandb-metadata.json
2020-11-18 10:29:16,381 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_created():212] file/dir created: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/requirements.txt
2020-11-18 10:29:16,522 DEBUG   Thread-11 :5137 [connectionpool.py:_make_request():452] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/mmvv/Paraphrasing%20with%20BART/x7es5chb/wandb-metadata.json?Expires=1605761955&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=lyeutlSNmIvveEBakKjn9v%2F4su9zntp8z8hcCdJurkgqP05WiXOIoLrlR5F9%2F1QkjAgghCgZ%2FoX1KIVo7lD8i%2F%2B8XAyqzCEceim0fMIhDDenxYXV3ilv3sAscj%2BUFxGoYPHqyyHGcWoDL8baGg24Sr%2Bh5rGsbtttn7lMIbu5doHwtIxse7uBFT32eXwMsUZRQra%2BTA8ca6aR%2BOLxqPyDcqOK5EQnq%2BMM41urgQcJhZ01Z9JxOFjobMqXbtaCmxEvGJ7%2BCvWEeLMYkhGlhG4tVrm6jq7MRjuTf3CYFCM05aG5AOtbMjn%2FSzW0i51jb6IJBaQhnX023BKbFcQsr1ol6g%3D%3D HTTP/1.1" 200 0
2020-11-18 10:29:16,528 INFO    Thread-11 :5137 [upload_job.py:push():131] Uploaded file /tmp/tmpdpvngqluwandb/2ydsdo6m-wandb-metadata.json
2020-11-18 10:29:17,386 DEBUG   Thread-5  :5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:29:17,756 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:29:18,712 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:29:21,033 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:29:22,383 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_created():212] file/dir created: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/media/graph/g.r.a.p.h._.0_summary_b416d011.graph.json
2020-11-18 10:29:22,384 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_created():212] file/dir created: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/media/graph
2020-11-18 10:29:22,385 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_created():212] file/dir created: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/media
2020-11-18 10:29:22,387 DEBUG   SenderThread:5137 [sender.py:send():90] send: files
2020-11-18 10:29:22,388 INFO    SenderThread:5137 [sender.py:_save_file():568] saving file media/graph/g.r.a.p.h._.0_summary_b416d011.graph.json with policy now
2020-11-18 10:29:22,389 DEBUG   SenderThread:5137 [sender.py:send():90] send: summary
2020-11-18 10:29:22,390 INFO    SenderThread:5137 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2020-11-18 10:29:22,405 DEBUG   Thread-12 :5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:29:22,806 DEBUG   Thread-12 :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:29:22,812 DEBUG   Thread-12 :5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): storage.googleapis.com:443
2020-11-18 10:29:23,124 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:29:23,384 INFO    Thread-8  :5137 [dir_watcher.py:_on_file_modified():225] file/dir modified: /home/medha/College/Sem5/IRE/Major_Project/HashtagGeneration/bert/wandb/run-20201118_102914-x7es5chb/files/wandb-summary.json
2020-11-18 10:29:23,424 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:29:23,436 DEBUG   Thread-12 :5137 [connectionpool.py:_make_request():452] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/mmvv/Paraphrasing%20with%20BART/x7es5chb/media/graph/g.r.a.p.h._.0_summary_b416d011.graph.json?Expires=1605761962&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=X4Yc4u4xEwKWDuZXOXNE6UanF9%2F17RadR647AyJBL5oAwsUZ8p4eGXh5Pm5yl05caHBMO1CsusIv9ouXNMQcElEwBC3bTlrPVeAmUSSeMJgSYGoMdt7k6zV01LyYuLVe1QfPZ07VSSL%2FgtDi6PZI%2BsCqAiW9d09bgLWFupgTS43NgcK6vO9vnEp4SSZE7VpwSD5N%2BucXZ%2BsqRYxzS8YoDqbhU723LNLBQjbIjV7XlmiJGFXKNh4nj4bOh4VQAp29j2R5u8ABosKeswu03Mcftbv219cViUmfl69XVdstvkuGZWP5ruzt8%2B485Q2UhcOFpmJU%2Bhn3BeKkiC%2BQQ5gYMg%3D%3D HTTP/1.1" 200 0
2020-11-18 10:29:23,438 INFO    Thread-12 :5137 [upload_job.py:push():131] Uploaded file /tmp/tmpdpvngqluwandb/23n99f2b-media/graph/g.r.a.p.h._.0_summary_b416d011.graph.json
2020-11-18 10:29:27,534 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:29:27,877 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:29:30,940 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: status
2020-11-18 10:29:30,941 DEBUG   SenderThread:5137 [sender.py:send():90] send: request
2020-11-18 10:29:30,941 DEBUG   SenderThread:5137 [sender.py:send_request():99] send_request: status
2020-11-18 10:29:30,945 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:29:31,340 DEBUG   SenderThread:5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:29:32,311 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:29:33,262 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:29:36,725 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:29:51,703 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: status
2020-11-18 10:29:58,224 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:29:58,476 DEBUG   SenderThread:5137 [sender.py:send():90] send: request
2020-11-18 10:29:58,476 DEBUG   SenderThread:5137 [sender.py:send_request():99] send_request: status
2020-11-18 10:30:07,353 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:30:19,374 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:30:38,661 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:30:47,238 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:30:54,766 DEBUG   SenderThread:5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:30:54,771 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:30:54,772 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:30:54,773 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:30:54,774 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:30:54,774 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:30:54,775 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:30:54,779 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:30:55,090 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:30:55,479 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:31:00,025 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:31:04,443 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:31:08,863 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:31:09,298 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:31:12,607 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: status
2020-11-18 10:31:12,608 DEBUG   SenderThread:5137 [sender.py:send():90] send: request
2020-11-18 10:31:12,608 DEBUG   SenderThread:5137 [sender.py:send_request():99] send_request: status
2020-11-18 10:31:12,772 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:31:52,211 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:32:35,158 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:33:04,778 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:33:37,848 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:33:43,640 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:34:04,508 ERROR   SenderThread:5137 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
2020-11-18 10:34:51,666 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:36:14,287 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:36:55,356 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:36:59,910 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:37:12,118 DEBUG   SenderThread:5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:37:13,063 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,064 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,065 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,065 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,067 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,068 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,068 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,069 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,070 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,070 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,071 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:13,071 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:15,980 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:37:16,495 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:21,975 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:27,339 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:37:28,309 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: status
2020-11-18 10:37:28,310 DEBUG   SenderThread:5137 [sender.py:send():90] send: request
2020-11-18 10:37:28,310 DEBUG   SenderThread:5137 [sender.py:send_request():99] send_request: status
2020-11-18 10:37:38,282 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:37:58,458 DEBUG   SenderThread:5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2020-11-18 10:38:04,393 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:38:08,149 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:38:08,184 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:38:08,261 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:38:19,951 DEBUG   SenderThread:5137 [sender.py:send():90] send: stats
2020-11-18 10:38:22,278 DEBUG   HandlerThread:5137 [handler.py:handle_request():55] handle_request: status
2020-11-18 10:38:23,646 DEBUG   SenderThread:5137 [sender.py:send():90] send: request
2020-11-18 10:38:23,647 DEBUG   SenderThread:5137 [sender.py:send_request():99] send_request: status
2020-11-18 10:38:28,835 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:38:55,295 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:39:08,251 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:39:52,252 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:39:54,545 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:40:15,915 ERROR   SenderThread:5137 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/medha/anaconda3/envs/transformers/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
2020-11-18 10:40:58,716 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:41:26,311 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:44:23,514 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:44:24,755 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:45:50,291 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:45:51,025 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
2020-11-18 10:48:38,403 DEBUG   Thread-5  :5137 [connectionpool.py:_make_request():452] https://api.wandb.ai:443 "POST /files/mmvv/Paraphrasing%20with%20BART/x7es5chb/file_stream HTTP/1.1" 200 None
2020-11-18 10:48:55,670 DEBUG   SenderThread:5137 [connectionpool.py:_new_conn():971] Starting new HTTPS connection (1): api.wandb.ai:443
